services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    container_name: server
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - .:/workspace
      - ~/.gitconfig.local:/root/.gitconfig.local
    working_dir: /workspace/server

  adminer:
    container_name: adminer
    depends_on:
      - db
    image: adminer:4
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data:
