FROM ruby:3.1.2-alpine

RUN apk add --no-cache \
  build-base \
  postgresql-dev \
  tzdata \
  gcompat

COPY /server/Gemfile ./
RUN bundle install --jobs=4 --retry=3
COPY /server .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]