FROM ruby:3.1.2-alpine

RUN apk add --no-cache \
  build-base \
  postgresql-dev \
  tzdata \
  gcompat

WORKDIR /bulletin-board

# COPY /server/Gemfile ./
# COPY /server/Gemfile.lock ./
COPY /server .
RUN bundle install --jobs=4 --retry=3

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]