version: "3"
services:
  server:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - 3000:3000
    depends_on:
      - db

    volumes:
      - .:/server

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./server/db/init:/docker-entrypoint-initdb.d
      - ./server/db/data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
