AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "db/migrate/**/*.rb"
