FROM ruby:3.1.2-alpine

RUN apk add --no-cache \
  git \
  build-base \
  postgresql-client \
  libpq-dev \
  tzdata \
  gcompat

WORKDIR /app

COPY / .
RUN bundle install --jobs=4 --retry=3

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]