# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.4'

gem 'rails', '~> 7.1.3', '>= 7.1.3.2'

gem 'sprockets-rails'

gem 'pg', '~> 1.1'

gem 'puma', '>= 5.0'

gem 'importmap-rails'

gem 'turbo-rails'

gem 'stimulus-rails'

gem 'jbuilder'

gem 'tzinfo-data', platforms: %i[mswin mswin64 mingw x64_mingw jruby]

gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'faker'
  gem 'rspec-rails', '~> 6.1.0'
  gem 'rubocop', require: false
end

group :development do
  gem 'web-console'

  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
  gem 'ruby-lsp', '0.13.2'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
end
